package io.xdea.xmux.forum.mapper;

import io.xdea.xmux.forum.model.LikedPost;
import io.xdea.xmux.forum.model.LikedPostExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface LikedPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.liked_post
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    long countByExample(LikedPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.liked_post
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    int deleteByExample(LikedPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.liked_post
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.liked_post
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    int insert(LikedPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.liked_post
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    int insertSelective(LikedPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.liked_post
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    List<LikedPost> selectByExampleWithRowbounds(LikedPostExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.liked_post
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    List<LikedPost> selectByExample(LikedPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.liked_post
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    LikedPost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.liked_post
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    int updateByExampleSelective(@Param("record") LikedPost record, @Param("example") LikedPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.liked_post
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    int updateByExample(@Param("record") LikedPost record, @Param("example") LikedPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.liked_post
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    int updateByPrimaryKeySelective(LikedPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.liked_post
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    int updateByPrimaryKey(LikedPost record);
}