package io.xdea.xmux.forum.mapper;

import io.xdea.xmux.forum.model.Member;
import io.xdea.xmux.forum.model.MemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.member
     *
     * @mbg.generated Wed Nov 06 17:40:56 CST 2024
     */
    long countByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.member
     *
     * @mbg.generated Wed Nov 06 17:40:56 CST 2024
     */
    int deleteByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.member
     *
     * @mbg.generated Wed Nov 06 17:40:56 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.member
     *
     * @mbg.generated Wed Nov 06 17:40:56 CST 2024
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.member
     *
     * @mbg.generated Wed Nov 06 17:40:56 CST 2024
     */
    int insertSelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.member
     *
     * @mbg.generated Wed Nov 06 17:40:56 CST 2024
     */
    List<Member> selectByExampleWithRowbounds(MemberExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.member
     *
     * @mbg.generated Wed Nov 06 17:40:56 CST 2024
     */
    List<Member> selectByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.member
     *
     * @mbg.generated Wed Nov 06 17:40:56 CST 2024
     */
    Member selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.member
     *
     * @mbg.generated Wed Nov 06 17:40:56 CST 2024
     */
    int updateByExampleSelective(@Param("record") Member record, @Param("example") MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.member
     *
     * @mbg.generated Wed Nov 06 17:40:56 CST 2024
     */
    int updateByExample(@Param("record") Member record, @Param("example") MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.member
     *
     * @mbg.generated Wed Nov 06 17:40:56 CST 2024
     */
    int updateByPrimaryKeySelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.member
     *
     * @mbg.generated Wed Nov 06 17:40:56 CST 2024
     */
    int updateByPrimaryKey(Member record);
}