package io.xdea.xmux.forum.mapper;

import io.xdea.xmux.forum.model.ReportType;
import io.xdea.xmux.forum.model.ReportTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface ReportTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.report_type
     *
     * @mbg.generated Wed Nov 06 17:40:56 CST 2024
     */
    long countByExample(ReportTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.report_type
     *
     * @mbg.generated Wed Nov 06 17:40:56 CST 2024
     */
    int deleteByExample(ReportTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.report_type
     *
     * @mbg.generated Wed Nov 06 17:40:56 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.report_type
     *
     * @mbg.generated Wed Nov 06 17:40:56 CST 2024
     */
    int insert(ReportType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.report_type
     *
     * @mbg.generated Wed Nov 06 17:40:56 CST 2024
     */
    int insertSelective(ReportType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.report_type
     *
     * @mbg.generated Wed Nov 06 17:40:56 CST 2024
     */
    List<ReportType> selectByExampleWithRowbounds(ReportTypeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.report_type
     *
     * @mbg.generated Wed Nov 06 17:40:56 CST 2024
     */
    List<ReportType> selectByExample(ReportTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.report_type
     *
     * @mbg.generated Wed Nov 06 17:40:56 CST 2024
     */
    ReportType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.report_type
     *
     * @mbg.generated Wed Nov 06 17:40:56 CST 2024
     */
    int updateByExampleSelective(@Param("record") ReportType record, @Param("example") ReportTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.report_type
     *
     * @mbg.generated Wed Nov 06 17:40:56 CST 2024
     */
    int updateByExample(@Param("record") ReportType record, @Param("example") ReportTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.report_type
     *
     * @mbg.generated Wed Nov 06 17:40:56 CST 2024
     */
    int updateByPrimaryKeySelective(ReportType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.report_type
     *
     * @mbg.generated Wed Nov 06 17:40:56 CST 2024
     */
    int updateByPrimaryKey(ReportType record);
}