package io.xdea.xmux.forum.mapper;

import io.xdea.xmux.forum.model.SavedPost;
import io.xdea.xmux.forum.model.SavedPostExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface SavedPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_post
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    long countByExample(SavedPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_post
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    int deleteByExample(SavedPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_post
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_post
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    int insert(SavedPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_post
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    int insertSelective(SavedPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_post
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    List<SavedPost> selectByExampleWithRowbounds(SavedPostExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_post
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    List<SavedPost> selectByExample(SavedPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_post
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    SavedPost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_post
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    int updateByExampleSelective(@Param("record") SavedPost record, @Param("example") SavedPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_post
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    int updateByExample(@Param("record") SavedPost record, @Param("example") SavedPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_post
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    int updateByPrimaryKeySelective(SavedPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_post
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    int updateByPrimaryKey(SavedPost record);
}