package io.xdea.xmux.forum.mapper;

import io.xdea.xmux.forum.model.SavedThread;
import io.xdea.xmux.forum.model.SavedThreadExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface SavedThreadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_thread
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    long countByExample(SavedThreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_thread
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    int deleteByExample(SavedThreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_thread
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_thread
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    int insert(SavedThread record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_thread
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    int insertSelective(SavedThread record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_thread
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    List<SavedThread> selectByExampleWithRowbounds(SavedThreadExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_thread
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    List<SavedThread> selectByExample(SavedThreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_thread
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    SavedThread selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_thread
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    int updateByExampleSelective(@Param("record") SavedThread record, @Param("example") SavedThreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_thread
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    int updateByExample(@Param("record") SavedThread record, @Param("example") SavedThreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_thread
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    int updateByPrimaryKeySelective(SavedThread record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_thread
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    int updateByPrimaryKey(SavedThread record);
}