package io.xdea.xmux.forum.mapper;

import io.xdea.xmux.forum.model.SavedReply;
import io.xdea.xmux.forum.model.SavedReplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface SavedReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_reply
     *
     * @mbg.generated Mon Jan 17 16:32:59 CST 2022
     */
    long countByExample(SavedReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_reply
     *
     * @mbg.generated Mon Jan 17 16:32:59 CST 2022
     */
    int deleteByExample(SavedReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_reply
     *
     * @mbg.generated Mon Jan 17 16:32:59 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_reply
     *
     * @mbg.generated Mon Jan 17 16:32:59 CST 2022
     */
    int insert(SavedReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_reply
     *
     * @mbg.generated Mon Jan 17 16:32:59 CST 2022
     */
    int insertSelective(SavedReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_reply
     *
     * @mbg.generated Mon Jan 17 16:32:59 CST 2022
     */
    List<SavedReply> selectByExampleWithRowbounds(SavedReplyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_reply
     *
     * @mbg.generated Mon Jan 17 16:32:59 CST 2022
     */
    List<SavedReply> selectByExample(SavedReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_reply
     *
     * @mbg.generated Mon Jan 17 16:32:59 CST 2022
     */
    SavedReply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_reply
     *
     * @mbg.generated Mon Jan 17 16:32:59 CST 2022
     */
    int updateByExampleSelective(@Param("record") SavedReply record, @Param("example") SavedReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_reply
     *
     * @mbg.generated Mon Jan 17 16:32:59 CST 2022
     */
    int updateByExample(@Param("record") SavedReply record, @Param("example") SavedReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_reply
     *
     * @mbg.generated Mon Jan 17 16:32:59 CST 2022
     */
    int updateByPrimaryKeySelective(SavedReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.saved_reply
     *
     * @mbg.generated Mon Jan 17 16:32:59 CST 2022
     */
    int updateByPrimaryKey(SavedReply record);
}