package com.flyingblu.community.model;

import java.util.Date;

public class Community {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.community.id
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.community.title
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.community.description
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.community.create_time
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.community.delete_time
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    private Date deleteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.community.id
     *
     * @return the value of community.community.id
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.community
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    public Community withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.community.id
     *
     * @param id the value for community.community.id
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.community.title
     *
     * @return the value of community.community.title
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.community
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    public Community withTitle(String title) {
        this.setTitle(title);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.community.title
     *
     * @param title the value for community.community.title
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.community.description
     *
     * @return the value of community.community.description
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.community
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    public Community withDescription(String description) {
        this.setDescription(description);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.community.description
     *
     * @param description the value for community.community.description
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.community.create_time
     *
     * @return the value of community.community.create_time
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.community
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    public Community withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.community.create_time
     *
     * @param createTime the value for community.community.create_time
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.community.delete_time
     *
     * @return the value of community.community.delete_time
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.community
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    public Community withDeleteTime(Date deleteTime) {
        this.setDeleteTime(deleteTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.community.delete_time
     *
     * @param deleteTime the value for community.community.delete_time
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.community
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", description=").append(description);
        sb.append(", createTime=").append(createTime);
        sb.append(", deleteTime=").append(deleteTime);
        sb.append("]");
        return sb.toString();
    }
}