package com.flyingblu.community.model;

import java.util.Date;

public class Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.post.id
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.post.uid
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.post.create_time
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.post.title
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.post.body
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    private String body;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.post.vote
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    private Integer vote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.post.community_id
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    private Integer communityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.post.topped
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    private Boolean topped;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.post.best
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    private Boolean best;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.post.delete_time
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    private Date deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.post.update_time
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.post.id
     *
     * @return the value of community.post.id
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.post
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public Post withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.post.id
     *
     * @param id the value for community.post.id
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.post.uid
     *
     * @return the value of community.post.uid
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.post
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public Post withUid(String uid) {
        this.setUid(uid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.post.uid
     *
     * @param uid the value for community.post.uid
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.post.create_time
     *
     * @return the value of community.post.create_time
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.post
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public Post withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.post.create_time
     *
     * @param createTime the value for community.post.create_time
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.post.title
     *
     * @return the value of community.post.title
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.post
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public Post withTitle(String title) {
        this.setTitle(title);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.post.title
     *
     * @param title the value for community.post.title
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.post.body
     *
     * @return the value of community.post.body
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.post
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public Post withBody(String body) {
        this.setBody(body);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.post.body
     *
     * @param body the value for community.post.body
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public void setBody(String body) {
        this.body = body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.post.vote
     *
     * @return the value of community.post.vote
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public Integer getVote() {
        return vote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.post
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public Post withVote(Integer vote) {
        this.setVote(vote);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.post.vote
     *
     * @param vote the value for community.post.vote
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public void setVote(Integer vote) {
        this.vote = vote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.post.community_id
     *
     * @return the value of community.post.community_id
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public Integer getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.post
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public Post withCommunityId(Integer communityId) {
        this.setCommunityId(communityId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.post.community_id
     *
     * @param communityId the value for community.post.community_id
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.post.topped
     *
     * @return the value of community.post.topped
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public Boolean getTopped() {
        return topped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.post
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public Post withTopped(Boolean topped) {
        this.setTopped(topped);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.post.topped
     *
     * @param topped the value for community.post.topped
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public void setTopped(Boolean topped) {
        this.topped = topped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.post.best
     *
     * @return the value of community.post.best
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public Boolean getBest() {
        return best;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.post
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public Post withBest(Boolean best) {
        this.setBest(best);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.post.best
     *
     * @param best the value for community.post.best
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public void setBest(Boolean best) {
        this.best = best;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.post.delete_time
     *
     * @return the value of community.post.delete_time
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.post
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public Post withDeleteTime(Date deleteTime) {
        this.setDeleteTime(deleteTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.post.delete_time
     *
     * @param deleteTime the value for community.post.delete_time
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.post.update_time
     *
     * @return the value of community.post.update_time
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.post
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public Post withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.post.update_time
     *
     * @param updateTime the value for community.post.update_time
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.post
     *
     * @mbg.generated Sat Jan 01 15:26:26 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", createTime=").append(createTime);
        sb.append(", title=").append(title);
        sb.append(", body=").append(body);
        sb.append(", vote=").append(vote);
        sb.append(", communityId=").append(communityId);
        sb.append(", topped=").append(topped);
        sb.append(", best=").append(best);
        sb.append(", deleteTime=").append(deleteTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}