package io.xdea.xmux.forum.model;

import java.util.Date;

public class Forum {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.forum.id
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.forum.title
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.forum.description
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.forum.create_at
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.forum.update_at
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.forum.creator_uid
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    private String creatorUid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.forum.id
     *
     * @return the value of forum.forum.id
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.forum
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    public Forum withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.forum.id
     *
     * @param id the value for forum.forum.id
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.forum.title
     *
     * @return the value of forum.forum.title
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.forum
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    public Forum withTitle(String title) {
        this.setTitle(title);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.forum.title
     *
     * @param title the value for forum.forum.title
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.forum.description
     *
     * @return the value of forum.forum.description
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.forum
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    public Forum withDescription(String description) {
        this.setDescription(description);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.forum.description
     *
     * @param description the value for forum.forum.description
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.forum.create_at
     *
     * @return the value of forum.forum.create_at
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.forum
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    public Forum withCreateAt(Date createAt) {
        this.setCreateAt(createAt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.forum.create_at
     *
     * @param createAt the value for forum.forum.create_at
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.forum.update_at
     *
     * @return the value of forum.forum.update_at
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.forum
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    public Forum withUpdateAt(Date updateAt) {
        this.setUpdateAt(updateAt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.forum.update_at
     *
     * @param updateAt the value for forum.forum.update_at
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.forum.creator_uid
     *
     * @return the value of forum.forum.creator_uid
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    public String getCreatorUid() {
        return creatorUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.forum
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    public Forum withCreatorUid(String creatorUid) {
        this.setCreatorUid(creatorUid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.forum.creator_uid
     *
     * @param creatorUid the value for forum.forum.creator_uid
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    public void setCreatorUid(String creatorUid) {
        this.creatorUid = creatorUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.forum
     *
     * @mbg.generated Mon Mar 14 20:41:03 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", description=").append(description);
        sb.append(", createAt=").append(createAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", creatorUid=").append(creatorUid);
        sb.append("]");
        return sb.toString();
    }
}