package io.xdea.xmux.forum.model;

import java.util.Date;

public class LikedPost {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.liked_post.id
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.liked_post.uid
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.liked_post.post_id
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    private Integer postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.liked_post.like
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    private Boolean like;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.liked_post.create_at
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    private Date createAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.liked_post.id
     *
     * @return the value of forum.liked_post.id
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.liked_post
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public LikedPost withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.liked_post.id
     *
     * @param id the value for forum.liked_post.id
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.liked_post.uid
     *
     * @return the value of forum.liked_post.uid
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.liked_post
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public LikedPost withUid(String uid) {
        this.setUid(uid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.liked_post.uid
     *
     * @param uid the value for forum.liked_post.uid
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.liked_post.post_id
     *
     * @return the value of forum.liked_post.post_id
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.liked_post
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public LikedPost withPostId(Integer postId) {
        this.setPostId(postId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.liked_post.post_id
     *
     * @param postId the value for forum.liked_post.post_id
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.liked_post.like
     *
     * @return the value of forum.liked_post.like
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public Boolean getLike() {
        return like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.liked_post
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public LikedPost withLike(Boolean like) {
        this.setLike(like);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.liked_post.like
     *
     * @param like the value for forum.liked_post.like
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public void setLike(Boolean like) {
        this.like = like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.liked_post.create_at
     *
     * @return the value of forum.liked_post.create_at
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.liked_post
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public LikedPost withCreateAt(Date createAt) {
        this.setCreateAt(createAt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.liked_post.create_at
     *
     * @param createAt the value for forum.liked_post.create_at
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.liked_post
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", postId=").append(postId);
        sb.append(", like=").append(like);
        sb.append(", createAt=").append(createAt);
        sb.append("]");
        return sb.toString();
    }
}