package io.xdea.xmux.forum.model;

import java.util.Date;
import java.util.Map;

public class Notif {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.notif.id
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.notif.uid
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.notif.sender_uid
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    private String senderUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.notif.create_at
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.notif.has_read
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    private Boolean hasRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.notif.type
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.notif.data
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    private Map data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.notif.id
     *
     * @return the value of forum.notif.id
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.notif
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    public Notif withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.notif.id
     *
     * @param id the value for forum.notif.id
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.notif.uid
     *
     * @return the value of forum.notif.uid
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.notif
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    public Notif withUid(String uid) {
        this.setUid(uid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.notif.uid
     *
     * @param uid the value for forum.notif.uid
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.notif.sender_uid
     *
     * @return the value of forum.notif.sender_uid
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    public String getSenderUid() {
        return senderUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.notif
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    public Notif withSenderUid(String senderUid) {
        this.setSenderUid(senderUid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.notif.sender_uid
     *
     * @param senderUid the value for forum.notif.sender_uid
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    public void setSenderUid(String senderUid) {
        this.senderUid = senderUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.notif.create_at
     *
     * @return the value of forum.notif.create_at
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.notif
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    public Notif withCreateAt(Date createAt) {
        this.setCreateAt(createAt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.notif.create_at
     *
     * @param createAt the value for forum.notif.create_at
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.notif.has_read
     *
     * @return the value of forum.notif.has_read
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    public Boolean getHasRead() {
        return hasRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.notif
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    public Notif withHasRead(Boolean hasRead) {
        this.setHasRead(hasRead);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.notif.has_read
     *
     * @param hasRead the value for forum.notif.has_read
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    public void setHasRead(Boolean hasRead) {
        this.hasRead = hasRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.notif.type
     *
     * @return the value of forum.notif.type
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.notif
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    public Notif withType(Integer type) {
        this.setType(type);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.notif.type
     *
     * @param type the value for forum.notif.type
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.notif.data
     *
     * @return the value of forum.notif.data
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    public Map getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.notif
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    public Notif withData(Map data) {
        this.setData(data);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.notif.data
     *
     * @param data the value for forum.notif.data
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    public void setData(Map data) {
        this.data = data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.notif
     *
     * @mbg.generated Sun Mar 27 20:25:58 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", senderUid=").append(senderUid);
        sb.append(", createAt=").append(createAt);
        sb.append(", hasRead=").append(hasRead);
        sb.append(", type=").append(type);
        sb.append(", data=").append(data);
        sb.append("]");
        return sb.toString();
    }
}