package io.xdea.xmux.forum.model;

import java.util.Date;

public class Notif {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.notif.id
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.notif.create_time
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.notif.uid
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.notif.type
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.notif.ref_id
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    private Integer refId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.notif.obj_id
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    private Integer objId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.notif.value
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    private Integer value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.notif.has_read
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    private Boolean hasRead;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.notif.id
     *
     * @return the value of forum.notif.id
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.notif
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    public Notif withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.notif.id
     *
     * @param id the value for forum.notif.id
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.notif.create_time
     *
     * @return the value of forum.notif.create_time
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.notif
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    public Notif withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.notif.create_time
     *
     * @param createTime the value for forum.notif.create_time
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.notif.uid
     *
     * @return the value of forum.notif.uid
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.notif
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    public Notif withUid(String uid) {
        this.setUid(uid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.notif.uid
     *
     * @param uid the value for forum.notif.uid
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.notif.type
     *
     * @return the value of forum.notif.type
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.notif
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    public Notif withType(Integer type) {
        this.setType(type);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.notif.type
     *
     * @param type the value for forum.notif.type
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.notif.ref_id
     *
     * @return the value of forum.notif.ref_id
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    public Integer getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.notif
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    public Notif withRefId(Integer refId) {
        this.setRefId(refId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.notif.ref_id
     *
     * @param refId the value for forum.notif.ref_id
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    public void setRefId(Integer refId) {
        this.refId = refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.notif.obj_id
     *
     * @return the value of forum.notif.obj_id
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    public Integer getObjId() {
        return objId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.notif
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    public Notif withObjId(Integer objId) {
        this.setObjId(objId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.notif.obj_id
     *
     * @param objId the value for forum.notif.obj_id
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    public void setObjId(Integer objId) {
        this.objId = objId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.notif.value
     *
     * @return the value of forum.notif.value
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.notif
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    public Notif withValue(Integer value) {
        this.setValue(value);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.notif.value
     *
     * @param value the value for forum.notif.value
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    public void setValue(Integer value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.notif.has_read
     *
     * @return the value of forum.notif.has_read
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    public Boolean getHasRead() {
        return hasRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.notif
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    public Notif withHasRead(Boolean hasRead) {
        this.setHasRead(hasRead);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.notif.has_read
     *
     * @param hasRead the value for forum.notif.has_read
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    public void setHasRead(Boolean hasRead) {
        this.hasRead = hasRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.notif
     *
     * @mbg.generated Sat Jan 22 21:57:46 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createTime=").append(createTime);
        sb.append(", uid=").append(uid);
        sb.append(", type=").append(type);
        sb.append(", refId=").append(refId);
        sb.append(", objId=").append(objId);
        sb.append(", value=").append(value);
        sb.append(", hasRead=").append(hasRead);
        sb.append("]");
        return sb.toString();
    }
}