package io.xdea.xmux.forum.model;

import java.util.Date;
import java.util.Map;

public class Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.id
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.uid
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.forum_id
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    private Integer forumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.thread_id
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    private Integer threadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.parent_id
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.ref_post_id
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    private Integer refPostId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.ref_post_uid
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    private String refPostUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.content_type
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    private Integer contentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.content
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    private Map content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.create_at
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.update_at
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.likes
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    private Integer likes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.pinned
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    private Boolean pinned;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.status
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.id
     *
     * @return the value of forum.post.id
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Post withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.id
     *
     * @param id the value for forum.post.id
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.uid
     *
     * @return the value of forum.post.uid
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Post withUid(String uid) {
        this.setUid(uid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.uid
     *
     * @param uid the value for forum.post.uid
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.forum_id
     *
     * @return the value of forum.post.forum_id
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Integer getForumId() {
        return forumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Post withForumId(Integer forumId) {
        this.setForumId(forumId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.forum_id
     *
     * @param forumId the value for forum.post.forum_id
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public void setForumId(Integer forumId) {
        this.forumId = forumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.thread_id
     *
     * @return the value of forum.post.thread_id
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Integer getThreadId() {
        return threadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Post withThreadId(Integer threadId) {
        this.setThreadId(threadId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.thread_id
     *
     * @param threadId the value for forum.post.thread_id
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public void setThreadId(Integer threadId) {
        this.threadId = threadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.parent_id
     *
     * @return the value of forum.post.parent_id
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Post withParentId(Integer parentId) {
        this.setParentId(parentId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.parent_id
     *
     * @param parentId the value for forum.post.parent_id
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.ref_post_id
     *
     * @return the value of forum.post.ref_post_id
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Integer getRefPostId() {
        return refPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Post withRefPostId(Integer refPostId) {
        this.setRefPostId(refPostId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.ref_post_id
     *
     * @param refPostId the value for forum.post.ref_post_id
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public void setRefPostId(Integer refPostId) {
        this.refPostId = refPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.ref_post_uid
     *
     * @return the value of forum.post.ref_post_uid
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public String getRefPostUid() {
        return refPostUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Post withRefPostUid(String refPostUid) {
        this.setRefPostUid(refPostUid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.ref_post_uid
     *
     * @param refPostUid the value for forum.post.ref_post_uid
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public void setRefPostUid(String refPostUid) {
        this.refPostUid = refPostUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.content_type
     *
     * @return the value of forum.post.content_type
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Integer getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Post withContentType(Integer contentType) {
        this.setContentType(contentType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.content_type
     *
     * @param contentType the value for forum.post.content_type
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public void setContentType(Integer contentType) {
        this.contentType = contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.content
     *
     * @return the value of forum.post.content
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Map getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Post withContent(Map content) {
        this.setContent(content);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.content
     *
     * @param content the value for forum.post.content
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public void setContent(Map content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.create_at
     *
     * @return the value of forum.post.create_at
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Post withCreateAt(Date createAt) {
        this.setCreateAt(createAt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.create_at
     *
     * @param createAt the value for forum.post.create_at
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.update_at
     *
     * @return the value of forum.post.update_at
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Post withUpdateAt(Date updateAt) {
        this.setUpdateAt(updateAt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.update_at
     *
     * @param updateAt the value for forum.post.update_at
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.likes
     *
     * @return the value of forum.post.likes
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Integer getLikes() {
        return likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Post withLikes(Integer likes) {
        this.setLikes(likes);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.likes
     *
     * @param likes the value for forum.post.likes
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public void setLikes(Integer likes) {
        this.likes = likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.pinned
     *
     * @return the value of forum.post.pinned
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Boolean getPinned() {
        return pinned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Post withPinned(Boolean pinned) {
        this.setPinned(pinned);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.pinned
     *
     * @param pinned the value for forum.post.pinned
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public void setPinned(Boolean pinned) {
        this.pinned = pinned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.status
     *
     * @return the value of forum.post.status
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public Post withStatus(Integer status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.status
     *
     * @param status the value for forum.post.status
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Thu Nov 07 10:00:12 CST 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", forumId=").append(forumId);
        sb.append(", threadId=").append(threadId);
        sb.append(", parentId=").append(parentId);
        sb.append(", refPostId=").append(refPostId);
        sb.append(", refPostUid=").append(refPostUid);
        sb.append(", contentType=").append(contentType);
        sb.append(", content=").append(content);
        sb.append(", createAt=").append(createAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", likes=").append(likes);
        sb.append(", pinned=").append(pinned);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}