package io.xdea.xmux.forum.model;

import java.util.Date;

public class Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.id
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.uid
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.thread_id
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    private Integer threadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.parent_id
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.ref_post_id
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    private Integer refPostId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.ref_post_uid
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    private String refPostUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.content
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.create_at
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.update_at
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.like
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    private Integer like;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.post.pinned
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    private Boolean pinned;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.id
     *
     * @return the value of forum.post.id
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public Post withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.id
     *
     * @param id the value for forum.post.id
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.uid
     *
     * @return the value of forum.post.uid
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public Post withUid(String uid) {
        this.setUid(uid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.uid
     *
     * @param uid the value for forum.post.uid
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.thread_id
     *
     * @return the value of forum.post.thread_id
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public Integer getThreadId() {
        return threadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public Post withThreadId(Integer threadId) {
        this.setThreadId(threadId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.thread_id
     *
     * @param threadId the value for forum.post.thread_id
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public void setThreadId(Integer threadId) {
        this.threadId = threadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.parent_id
     *
     * @return the value of forum.post.parent_id
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public Post withParentId(Integer parentId) {
        this.setParentId(parentId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.parent_id
     *
     * @param parentId the value for forum.post.parent_id
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.ref_post_id
     *
     * @return the value of forum.post.ref_post_id
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public Integer getRefPostId() {
        return refPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public Post withRefPostId(Integer refPostId) {
        this.setRefPostId(refPostId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.ref_post_id
     *
     * @param refPostId the value for forum.post.ref_post_id
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public void setRefPostId(Integer refPostId) {
        this.refPostId = refPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.ref_post_uid
     *
     * @return the value of forum.post.ref_post_uid
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public String getRefPostUid() {
        return refPostUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public Post withRefPostUid(String refPostUid) {
        this.setRefPostUid(refPostUid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.ref_post_uid
     *
     * @param refPostUid the value for forum.post.ref_post_uid
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public void setRefPostUid(String refPostUid) {
        this.refPostUid = refPostUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.content
     *
     * @return the value of forum.post.content
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public Post withContent(String content) {
        this.setContent(content);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.content
     *
     * @param content the value for forum.post.content
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.create_at
     *
     * @return the value of forum.post.create_at
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public Post withCreateAt(Date createAt) {
        this.setCreateAt(createAt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.create_at
     *
     * @param createAt the value for forum.post.create_at
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.update_at
     *
     * @return the value of forum.post.update_at
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public Post withUpdateAt(Date updateAt) {
        this.setUpdateAt(updateAt);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.update_at
     *
     * @param updateAt the value for forum.post.update_at
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.like
     *
     * @return the value of forum.post.like
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public Integer getLike() {
        return like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public Post withLike(Integer like) {
        this.setLike(like);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.like
     *
     * @param like the value for forum.post.like
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public void setLike(Integer like) {
        this.like = like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.post.pinned
     *
     * @return the value of forum.post.pinned
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public Boolean getPinned() {
        return pinned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public Post withPinned(Boolean pinned) {
        this.setPinned(pinned);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.post.pinned
     *
     * @param pinned the value for forum.post.pinned
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    public void setPinned(Boolean pinned) {
        this.pinned = pinned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.post
     *
     * @mbg.generated Mon Mar 07 13:48:24 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", threadId=").append(threadId);
        sb.append(", parentId=").append(parentId);
        sb.append(", refPostId=").append(refPostId);
        sb.append(", refPostUid=").append(refPostUid);
        sb.append(", content=").append(content);
        sb.append(", createAt=").append(createAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", like=").append(like);
        sb.append(", pinned=").append(pinned);
        sb.append("]");
        return sb.toString();
    }
}