package io.xdea.xmux.forum.model;

public class ReportType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.report_type.id
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.report_type.name
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.report_type.id
     *
     * @return the value of forum.report_type.id
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.report_type
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    public ReportType withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.report_type.id
     *
     * @param id the value for forum.report_type.id
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.report_type.name
     *
     * @return the value of forum.report_type.name
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.report_type
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    public ReportType withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.report_type.name
     *
     * @param name the value for forum.report_type.name
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forum.report_type
     *
     * @mbg.generated Mon Nov 04 19:59:07 CST 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append("]");
        return sb.toString();
    }
}