package com.flyingblu.community.mapper;

import com.flyingblu.community.model.Community;
import com.flyingblu.community.model.CommunityExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface CommunityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.community
     *
     * @mbg.generated Thu Dec 30 18:47:49 CST 2021
     */
    long countByExample(CommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.community
     *
     * @mbg.generated Thu Dec 30 18:47:49 CST 2021
     */
    int deleteByExample(CommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.community
     *
     * @mbg.generated Thu Dec 30 18:47:49 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.community
     *
     * @mbg.generated Thu Dec 30 18:47:49 CST 2021
     */
    int insert(Community record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.community
     *
     * @mbg.generated Thu Dec 30 18:47:49 CST 2021
     */
    int insertSelective(Community record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.community
     *
     * @mbg.generated Thu Dec 30 18:47:49 CST 2021
     */
    List<Community> selectByExampleWithRowbounds(CommunityExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.community
     *
     * @mbg.generated Thu Dec 30 18:47:49 CST 2021
     */
    List<Community> selectByExample(CommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.community
     *
     * @mbg.generated Thu Dec 30 18:47:49 CST 2021
     */
    Community selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.community
     *
     * @mbg.generated Thu Dec 30 18:47:49 CST 2021
     */
    int updateByExampleSelective(@Param("record") Community record, @Param("example") CommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.community
     *
     * @mbg.generated Thu Dec 30 18:47:49 CST 2021
     */
    int updateByExample(@Param("record") Community record, @Param("example") CommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.community
     *
     * @mbg.generated Thu Dec 30 18:47:49 CST 2021
     */
    int updateByPrimaryKeySelective(Community record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.community
     *
     * @mbg.generated Thu Dec 30 18:47:49 CST 2021
     */
    int updateByPrimaryKey(Community record);
}