package com.flyingblu.community.mapper;

import com.flyingblu.community.model.Moderate;
import com.flyingblu.community.model.ModerateExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface ModerateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.moderate
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    long countByExample(ModerateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.moderate
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    int deleteByExample(ModerateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.moderate
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.moderate
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    int insert(Moderate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.moderate
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    int insertSelective(Moderate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.moderate
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    List<Moderate> selectByExampleWithRowbounds(ModerateExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.moderate
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    List<Moderate> selectByExample(ModerateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.moderate
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    Moderate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.moderate
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    int updateByExampleSelective(@Param("record") Moderate record, @Param("example") ModerateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.moderate
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    int updateByExample(@Param("record") Moderate record, @Param("example") ModerateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.moderate
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    int updateByPrimaryKeySelective(Moderate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.moderate
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    int updateByPrimaryKey(Moderate record);
}