package com.flyingblu.community.mapper;

import com.flyingblu.community.model.Post;
import com.flyingblu.community.model.PostExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface PostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.post
     *
     * @mbg.generated Sat Jan 01 16:50:27 CST 2022
     */
    long countByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.post
     *
     * @mbg.generated Sat Jan 01 16:50:27 CST 2022
     */
    int deleteByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.post
     *
     * @mbg.generated Sat Jan 01 16:50:27 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.post
     *
     * @mbg.generated Sat Jan 01 16:50:27 CST 2022
     */
    int insert(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.post
     *
     * @mbg.generated Sat Jan 01 16:50:27 CST 2022
     */
    int insertSelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.post
     *
     * @mbg.generated Sat Jan 01 16:50:27 CST 2022
     */
    List<Post> selectByExampleWithRowbounds(PostExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.post
     *
     * @mbg.generated Sat Jan 01 16:50:27 CST 2022
     */
    List<Post> selectByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.post
     *
     * @mbg.generated Sat Jan 01 16:50:27 CST 2022
     */
    Post selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.post
     *
     * @mbg.generated Sat Jan 01 16:50:27 CST 2022
     */
    int updateByExampleSelective(@Param("record") Post record, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.post
     *
     * @mbg.generated Sat Jan 01 16:50:27 CST 2022
     */
    int updateByExample(@Param("record") Post record, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.post
     *
     * @mbg.generated Sat Jan 01 16:50:27 CST 2022
     */
    int updateByPrimaryKeySelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.post
     *
     * @mbg.generated Sat Jan 01 16:50:27 CST 2022
     */
    int updateByPrimaryKey(Post record);
}