package com.flyingblu.community.mapper;

import com.flyingblu.community.model.Reply;
import com.flyingblu.community.model.ReplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface ReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.reply
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    long countByExample(ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.reply
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    int deleteByExample(ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.reply
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.reply
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    int insert(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.reply
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    int insertSelective(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.reply
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    List<Reply> selectByExampleWithRowbounds(ReplyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.reply
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    List<Reply> selectByExample(ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.reply
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    Reply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.reply
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    int updateByExampleSelective(@Param("record") Reply record, @Param("example") ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.reply
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    int updateByExample(@Param("record") Reply record, @Param("example") ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.reply
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    int updateByPrimaryKeySelective(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community.reply
     *
     * @mbg.generated Thu Dec 30 16:05:56 CST 2021
     */
    int updateByPrimaryKey(Reply record);
}